package io.nimbus.platform.audit.domain;

/**
 * 감사 이벤트 액션. PRD v1.5A audit_log action 예시 확장.
 */
public enum AuditAction {
    LOGIN,
    LOGOUT,
    SWITCH_WORKSPACE,

    CREATE_WORKSPACE,
    UPDATE_WORKSPACE,
    INVITE_MEMBER,
    UPDATE_MEMBER_ROLE,
    REMOVE_MEMBER,

    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    ARCHIVE_PROJECT,
    RESTORE_PROJECT,

    CREATE_WIZARD,
    UPDATE_WIZARD,
    EXECUTE_WIZARD,
    RETRY_WIZARD,
    CANCEL_WIZARD,

    CONNECT_GITHUB,
    DISCONNECT_GITHUB,

    CREATE_PIPELINE,
    RERUN_PIPELINE,

    CREATE_ENVIRONMENT,
    UPDATE_ENVIRONMENT,
    DELETE_ENVIRONMENT,
    ARCHIVE_ENVIRONMENT,
    RESTORE_ENVIRONMENT,
    PROMOTE_ENVIRONMENT,

    CREATE_VARIABLE,
    UPDATE_VARIABLE,
    DELETE_VARIABLE,
    CREATE_SECRET,
    UPDATE_SECRET,
    DELETE_SECRET,
    REVEAL_SECRET,
    SYNC_GITHUB_SECRETS,
    ROTATE_SECRET,

    RECORD_DEPLOYMENT,

    OPEN_INCIDENT,
    ACK_INCIDENT,
    RESOLVE_INCIDENT,

    DEPLOY_K8S,
    DELETE_K8S
}
