package io.nimbus.platform.environment.service;

import io.nimbus.platform.auth.security.NimbusPrincipal;
import io.nimbus.platform.environment.domain.ServiceEnvironment;
import io.nimbus.platform.github.domain.GitHubConnection;
import io.nimbus.platform.github.provider.GitProvider;
import io.nimbus.platform.github.service.GitHubConnectionService;
import io.nimbus.platform.serviceapp.domain.AppService;
import io.nimbus.platform.serviceapp.domain.EnvironmentType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.Locale;
import java.util.Optional;

/**
 * Thin GitOps on promote: branch meta always; real PR only when SCM + repo + branches work.
 * Failure falls back to SIMULATED (never blocks promote).
 */
@Service
public class PromoteGitOpsService {

    private static final Logger log = LoggerFactory.getLogger(PromoteGitOpsService.class);

    private final GitHubConnectionService connectionService;
    private final GitProvider gitProvider;

    public PromoteGitOpsService(GitHubConnectionService connectionService, GitProvider gitProvider) {
        this.connectionService = connectionService;
        this.gitProvider = gitProvider;
    }

    public GitOpsResult resolve(
            NimbusPrincipal principal,
            AppService service,
            ServiceEnvironment source,
            ServiceEnvironment target
    ) {
        String head = branchOf(source);
        String base = branchOf(target);
        String title = "nimbus: promote " + source.getType() + " → " + target.getType()
                + " (" + service.getName() + ")";
        String body = """
                ## Nimbus Promote

                - Service: `%s`
                - Path: **%s → %s**
                - Head: `%s`
                - Base: `%s`

                Generated by Nimbus Platform (thin GitOps).
                """.formatted(
                service.getName(),
                source.getType(),
                target.getType(),
                head,
                base
        );

        String owner = service.getGithubOwner();
        String repo = service.getGithubRepoName();
        Optional<GitHubConnection> connection = connectionService.findActiveEntity(principal.userId());
        boolean canLive = connection.isPresent()
                && owner != null && !owner.isBlank()
                && repo != null && !repo.isBlank();

        if (!canLive) {
            String why = connection.isEmpty()
                    ? "GitHub SCM 미연결"
                    : "서비스에 GitHub repo 바인딩 없음";
            return new GitOpsResult("SIMULATED", head, base, null, null, why);
        }

        try {
            String token = connectionService.decryptToken(connection.get());
            GitProvider.CreatedPullRequest pr = gitProvider.createPullRequest(
                    token, owner, repo, title, body, head, base
            );
            return new GitOpsResult(
                    "PR_CREATED",
                    head,
                    base,
                    pr.htmlUrl(),
                    pr.number() > 0 ? pr.number() : null,
                    "PR #" + pr.number()
            );
        } catch (Exception ex) {
            log.info("Promote GitOps PR simulated after failure: {}", ex.getMessage());
            // Branches often missing in free-only — still record intended head/base
            return new GitOpsResult(
                    "BRANCH_RECORDED",
                    head,
                    base,
                    null,
                    null,
                    "PR 생성 실패 → branch meta만 기록: " + truncate(ex.getMessage())
            );
        }
    }

    private static String branchOf(ServiceEnvironment env) {
        if (env.getGitOpsBranch() != null && !env.getGitOpsBranch().isBlank()) {
            return env.getGitOpsBranch().trim();
        }
        return ServiceEnvironment.defaultBranch(env.getType() != null ? env.getType() : EnvironmentType.DEV);
    }

    private static String truncate(String s) {
        if (s == null) return "";
        String one = s.replace('\n', ' ').trim();
        return one.length() > 160 ? one.substring(0, 160) : one;
    }

    public record GitOpsResult(
            String mode,
            String headBranch,
            String baseBranch,
            String pullRequestUrl,
            Integer pullRequestNumber,
            String detail
    ) {
        public String modeLabel() {
            return mode != null ? mode.toUpperCase(Locale.ROOT) : "SIMULATED";
        }
    }
}
